# Human-readable description for the project
project_id = "ufeqnnbokyalwjfskhmw"

[functions]
  [functions.signup]
    verify_jwt = false
  [functions.signin]
    verify_jwt = false
  [functions.profile]
    verify_jwt = false
  [functions.artisans]
    verify_jwt = false
  [functions.professionals]
    verify_jwt = false
  [functions.reviews]
    verify_jwt = false
  [functions.migrate-users]
    verify_jwt = false
  [functions.conversations]
    verify_jwt = false
  [functions.logout]
    verify_jwt = false